name: Taiga-Spettro
description: |
  Project management platform for agile developers
version: # Version of the Catalog to be used
category: Agile
maintainer: spettro.io
license: Private
projectURL: www.spettro.io
